[tool.poetry]
name = "paperoni"
version = "0.1.8"
description = "Search for scientific papers"
authors = ["Olivier Breuleux <breuleux@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/mila-iqia/paperoni"
repository = "https://github.com/mila-iqia/paperoni"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.9.1"
blessed = "^1.17.9"
coleo = {extras = ["yaml"], version = "^0.3.2"}
eventlet = "^0.33.1"
giving = "^0.4.1"
lxml = "^4.9.1"
openreview-py = "^1.5.2,<1.28.0"
ovld = "^0.3.5"
pydantic = "^1.9.1"
questionary = "^1.10.0"
requests = "^2.24.0"
requests-cache = "^0.9.6"
rich = "^12.5.1"
SQLAlchemy = "^1.4.39"
tqdm = "^4.48.2"
fake-useragent = "^1.1.3"
grizzlaxy = "^0.3.4"
starbear = "^0.1.6"
html5lib = "^1.1"
aiostream = "^0.5.0"
sentry-sdk = {extras = ["starlette"], version = "^1.31.0"}
markdown = "^3.4.4"
gifnoc = "^0.3.3"
backoff = "^2.2.1"
unidecode = "^1.3.8"
python-multipart = "^0.0.9"
bibtexparser = "2.0.0b7"

[tool.poetry.group.dev.dependencies]
pip-tools = "^7.4.1"
pytest = ">= 7.1.3"
pytest-cov = ">= 3.0.0"
pytest-regressions = "^2.4.1"
ruff = "^0.3.7"

[tool.poetry.scripts]
paperoni = "paperoni.cli:main"

[tool.ruff]
line-length = 80

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["E241", "F722", "E501", "E203", "F811", "F821", "E741"]

[tool.ruff.lint.isort]
combine-as-imports = true

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.report]
exclude_lines = [
    "covguard",
    "covguard_fn",
    "# pragma: no cover"
]
