[project]
name = "paperoni"
version = "0.1.8"
description = "Search for scientific papers"
authors = [
    { name = "Olivier Breuleux", email = "breuleux@gmail.com" }
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
dependencies = [
    "coleo>=0.3.4",
    "gifnoc>=0.4.0",
    "giving>=0.4.3",
    "ovld>=0.4.2",
    "requests>=2.32.3",
    "requests-cache>=1.2.1",
    "sqlalchemy~=1.4",
    "starbear[server]>=0.2.2",
    "eventlet>=0.37.0",
    "tqdm>=4.66.5",
    "pydantic<2.0.0",
    "unidecode>=1.3.8",
    "questionary>=2.0.1",
    "fake-useragent>=1.5.1",
    "backoff>=2.2.1",
    "bibtexparser>=1.4.1",
    "python-multipart>=0.0.9",
    "sentry-sdk[starlette]>=2.14.0",
    "rich>=13.8.1",
    "openreview-py>=1.43.2",
    "lxml>=5.3.0",
    "aiostream>=0.6.2",
    "html5lib>=1.1",
    "beautifulsoup4>=4.12.3",
    "blessed>=1.20.0",
    "markdown>=3.7",
]

[project.urls]
Homepage = "https://github.com/mila-iqia/paperoni"
Repository = "https://github.com/mila-iqia/paperoni"

[project.scripts]
paperoni = "paperoni.cli:main"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
    "pytest-cov>=5.0.0",
    "pytest-regressions>=2.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 80

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["E241", "F722", "E501", "E203", "F811", "F821", "E741"]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.coverage.report]
exclude_lines = [
    "covguard",
    "covguard_fn",
    "# pragma: no cover"
]
