---
- name: Install
  import_role:
    name: pyservice
    tasks_from: setup

- name: Template config
  become: true
  ansible.builtin.template:
    src: "config.yaml"
    dest: "{{ app_config }}"
    owner: "{{ app_user }}"
    mode: "0600"

- name: Activate
  import_role:
    name: pyservice
    tasks_from: activate
